### ISSUE TITLE
Swift 1.2

### ISSUE THREAD

**Issue by flessard** [malczak/hashids#1]
Compatible to Swift 1.2

**Comment by flessard** [comment]
Any news ?

**Comment by malczak** [comment]
Hi sorry missed the mesaage in notifications. Not yet will be reviewed and updated on days.

**Comment by flessard** [comment]
Thanks !  :)

**Comment by jonathanxie** [comment]
Made some changes at this branch and made a PR:

https://github.com/jonathanxie/hashids

Tested it in my app with the following code:

``` Swift
        var hashids = Hashids(salt:"!!!this is my salt!!!");
        var hash = hashids.encode(1, 2, 3); // hash:"DBCQcl"
        var values = hashids.decode(hash); // values:[1,2,3]

        println("hash = \(hash)")
        println("values = \(values)")
```

And got this output:

```
hash = Optional("DBCQcl")
values = [1, 2, 3]
```

Created a PR...

@flessard and @malczak, hope this helps. FYI...I didn't run HashIdsTests.swift though...

**Comment by malczak** [comment]
Hi, thanks I already fixed all incompatibilities but coudn't find time to merge it to master. Already done. Thanks for your comments.
