### ISSUE TITLE
Empty Salt not supported

### ISSUE THREAD

**Issue by matthiasotto** [malczak/hashids#13]
Unlike the Java and JS equivalents this implementation doesn't appear to support empty salts:

`let hashids = Hashids(salt:"", minHashLength: 20)`
throws:
`Fatal error: Remainder of division by zero`

**Comment by matthiasotto** [comment]
This fork seems to have made the salt optional. 

https://github.com/xw901103/hashids/commit/0067e7cc37d42d7d66e6cb3df87738c296277b3a

**Comment by malczak** [comment]
Thanks for pointing this out, fixed with c27a29f294989ee87b17c515bfcfa21cf830dd76
