### ISSUE TITLE
Encoding incorrectly

### ISSUE THREAD

**Issue by andrewtweber** [malczak/hashids#15]
```swift
let hashids = Hashids(salt: "icaslntrigresnisteet", minHashLength: 32, alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890");
hash = hashids.encode(1, 2, 8)
```

In Swift this yields:
`n1EOZmo3bKArd9YcphPd742kWewMpvPR`

In PHP (specifically with Laravel config)

```php
'main' => [
    'salt'     => 'icaslntrigresnisteet',
    'length'   => 32,
    'alphabet' => 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890',
],
```

PHP yields:
`n1EOZmo3bKArd9YCpHPd742kWewMpvPR`

Notice that the C and H are lowercase in Swift but uppercase in PHP. This is really concerning... if I can't trust that the hashes are the same in Swift and PHP then I can't use this at all.

The `1, 2, 8` is just one example. I've tried many other numbers and the hash is always incorrect. It's always the two letters in position 16 and 18 that are lowercase and should be uppercase.

**Comment by andrewtweber** [comment]
I removed the capital letters from the alphabet and that has fixed it... so shady though. Please investigate

Should also note that I tried a couple different salts with the same result

**Comment by kurabi** [comment]
Javascript library also matches the PHP output. @malczak Any idea what you think the issue is?

**Comment by malczak** [comment]
@kurabi @andrewtweber no idea. we have investigated this in past but not clear answer. I will revisit this an test against php and javascript

**Comment by andrewtweber** [comment]
Bravo, thank you!
