### ISSUE TITLE
Swift 2.2 Support

### ISSUE THREAD

**Issue by skela** [malczak/hashids#8]
There's 6 simple warnings for this library when used on Swift 2.2.

![screen shot 2016-03-23 at 14 49 00](https://cloud.githubusercontent.com/assets/58268/13977752/98922eae-f106-11e5-8b25-0179c5d2b342.png)

**Comment by malczak** [comment]
Thanks for pointing it out. Will be updated in following days.

**Comment by malczak** [comment]
Code updated and all warnings removed. Thanks.
