### ISSUE TITLE
Support Swift 3

### ISSUE THREAD

**Issue by lemonnm** [malczak/hashids#9]
Hi!

I try Hashids with Swift3 and there are many error :  

<img width="288" alt="hashidserrors" src="https://cloud.githubusercontent.com/assets/2083594/18343709/bd37c8b2-75b4-11e6-9ec6-144d188074f7.png">

**Comment by lucosi** [comment]
I have the same issue. I hope the guys update the code soon.

**Comment by malczak** [comment]
Hi guys update is in progress. Will be soon available on a new branch

**Comment by skela** [comment]
Same here, waiting for it :D

**Comment by malczak** [comment]
Done. Are tests are passing, but in case of problems please report any issues.

**Comment by k3zi** [comment]
@malczak Would the .podspec need to be bumped as well? I think it's pointing to the 0.3.1 (Swift 2.2) release now.

**Comment by ThomasKlickermann** [comment]
update doesn't conform to other hashids libraries ...

try using generated hash from swift and decode with php or js library of hashids.

**Comment by haithngnbak** [comment]
Error:(283, 90) 'Index' is not a member type of 'U'
Error:(283, 106) 'Iterator' is not a member type of 'U'
Error:(317, 87) 'Iterator' is not a member type of 'T'
Error:(317, 53) 'Iterator' is not a member type of 'T'
Error:(321, 164) 'Iterator' is not a member type of 'T'
Error:(321, 78) 'Iterator' is not a member type of 'T'
Error:(321, 138) 'Iterator' is not a member type of 'T'
Error:(330, 76) 'Iterator' is not a member type of 'T'
Error:(330, 50) 'Iterator' is not a member type of 'T'
Error:(339, 90) 'Iterator' is not a member type of 'T'
Error:(339, 64) 'Iterator' is not a member type of 'T'
Error:(348, 88) 'Iterator' is not a member type of 'T'
Error:(348, 62) 'Iterator' is not a member type of 'T'
Error:(356, 170) 'Iterator' is not a member type of 'U'
Error:(356, 201) 'Index' is not a member type of 'U'
Error:(361, 195) 'Iterator' is not a member type of 'U'
Error:(361, 226) 'Index' is not a member type of 'U'
Error:(92, 17) cannot pass immutable value of type 'inout [T]' (aka 'inout Array<T>') as inout argument
Error:(117, 17) cannot pass immutable value of type 'inout [T]' (aka 'inout Array<T>') as inout argument
Error:(196, 21) cannot pass immutable value of type 'inout [T]' (aka 'inout Array<T>') as inout argument
Error:(225, 21) cannot pass immutable value of type 'inout [T]' (aka 'inout Array<T>') as inout argument
Error:(286, 43) value of type 'U' has no member 'count'
Error:(289, 21) value of type 'U' has no member 'reduce'
Error:(322, 21) 'Iterator' is not a member type of 'T'
Error:(324, 14) type of expression is ambiguous without more context
Error:(357, 38) value of type 'U' has no member 'count'
Error:(366, 39) type 'U' has no subscript members
Error:(283, 90) 'Index' is not a member type of 'U'
Error:(283, 106) 'Iterator' is not a member type of 'U'

**Comment by lemonlab** [comment]
I think you should reopen this issue as there are still lots of errors with Swift 3.2.

**Comment by lemonlab** [comment]
Sorry, i was using the wrong pod
`pod 'Hashids-Swift', :git => 'https://github.com/malczak/hashids.git', :commit => '34170e1'`
works well. Thank you.
